[tool.poetry]
name = "autowebbot"
version = "0.1.0"
description = ""
authors = ["Seunggyu_Baek <tmdrbpp123@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
selenium = "^4.27.1"
webdriver-manager = "^4.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
